kafka-lag-exporter {
  poll-interval = 5 seconds
  reporters.prometheus.port = 8000
  clusters = [
    {
      name = "a-cluster"
      bootstrap-brokers = "broker-1:9092",
      labels = {
        namespace = "foo"
      }
    }
  ]
}
